ALTER TABLE five_s_audit_overrides
  ADD COLUMN IF NOT EXISTS action_required TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS owner TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS due_date TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT '';
